#!/usr/bin/env python3
"""던전 페이지(/en/dungeons/<slug>)에서 보스 드랍과 퀘스트 보상을 뽑아 DungeonData.lua 를 만든다.

사용법:  python tools/extract_dungeon_data.py --out DungeonData.lua [--cache DIR]
페이지의 Next.js flight 데이터(self.__next_f.push)에 들어 있는 loot / rewardQuests / quests 를 읽는다.
"""
import re, json, sys, argparse, urllib.request
from pathlib import Path

import os
BASE = os.environ.get("DUNGEON_DATA_BASE", "")   # 데이터를 가져올 사이트 주소 (예: https://example.com/en)
SLUGS = []   # 비어 있으면 던전 목록 페이지에서 자동으로 찾는다
KO = {"Dalaran": "달라란", "Deadmines": "죽음의 폐광", "The Deadmines": "죽음의 폐광", "Shadowfang Keep": "그림자송곳니 성채", "Stockade": "스톰윈드 지하감옥", "The Stockade": "스톰윈드 지하감옥", "Razorfen Downs": "가시덩굴 구릉", "Uldaman": "울다만", "Ragefire Chasm": "성난불길 협곡", "Scarlet Monastery Armory": "붉은십자군 수도원", "Scarlet Monastery Cathedral": "붉은십자군 수도원", "Scarlet Monastery Graveyard": "붉은십자군 수도원", "Scarlet Monastery Library": "붉은십자군 수도원", "Ruins Of Lordaeron": "로데론의 폐허", "Ruins of Lordaeron": "로데론의 폐허", "Excavation Site": "발굴 현장: 저습지", "Hall Of Thanes": "영주의 전당", "Hall of Thanes": "영주의 전당", "The Hall of Thanes": "영주의 전당", "Wailing Caverns": "통곡의 동굴", "Blackfathom Deeps": "검은심연의 나락", "Gnomeregan": "놈리건", "Razorfen Kraul": "가시덩굴 우리"}

def discover(cache):
    p = Path(cache) / "_dungeons.html" if cache else None
    if p and p.exists():
        h = p.read_text(encoding="utf-8")
    else:
        req = urllib.request.Request(f"{BASE}/dungeons", headers={"User-Agent": "Mozilla/5.0 BestGearFinder-data"})
        h = urllib.request.urlopen(req, timeout=60).read().decode("utf-8")
        if p:
            p.parent.mkdir(parents=True, exist_ok=True); p.write_text(h, encoding="utf-8")
    seen = []
    for m in re.finditer(r'href="[^"]*/dungeons/([a-z0-9-]+)"', h):
        if m.group(1) not in seen: seen.append(m.group(1))
    return seen

def fetch(slug, cache):
    p = Path(cache) / f"{slug}.html" if cache else None
    if p and p.exists():
        return p.read_text(encoding="utf-8")
    req = urllib.request.Request(f"{BASE}/dungeons/{slug}", headers={"User-Agent": "Mozilla/5.0 BestGearFinder-data"})
    h = urllib.request.urlopen(req, timeout=60).read().decode("utf-8")
    if p:
        p.parent.mkdir(parents=True, exist_ok=True); p.write_text(h, encoding="utf-8")
    return h

def flight(h):
    parts = re.findall(r'self\.__next_f\.push\(\[1,"(.*?)"\]\)</script>', h, flags=re.S)
    return "".join(json.loads('"' + p + '"') for p in parts)

def find_array(t, key, start=0):
    i = t.find(f'"{key}":[', start)
    if i < 0: return None, -1
    j = i + len(key) + 3
    dec = json.JSONDecoder()
    arr, end = dec.raw_decode(t[j:])
    return arr, j + end

def clean(v):
    return None if v == "$undefined" else v

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="DungeonData.lua")
    ap.add_argument("--cache")
    a = ap.parse_args()
    drops, quests, names = {}, {}, {}
    for slug in (SLUGS or discover(a.cache)):
        try:
            t = flight(fetch(slug, a.cache))
        except Exception as e:
            print("skip", slug, e, file=sys.stderr); continue
        m = re.search(r'"dungeon":\{[^{}]*?"name":"([^"]+)"', t) or re.search(r'"title":"([^"]+)","slug":"%s"' % slug, t)
        inst = slug.replace("-", " ").title()
        mm = re.search(r'"slug":"%s","name":"([^"]+)"' % re.escape(slug), t)
        if mm: inst = mm.group(1)
        inst = KO.get(inst, inst)
        loot, _ = find_array(t, "loot")
        n1 = n2 = 0
        for it in loot or []:
            iid = it.get("id"); boss = clean(it.get("bossName")) or clean(it.get("boss"))
            if not isinstance(iid, int) or not boss: continue
            lst = drops.setdefault(iid, [])
            if not any(x["boss"] == boss and x["inst"] == inst for x in lst):
                lst.append({"inst": inst, "boss": boss}); n1 += 1
        rq, _ = find_array(t, "rewardQuests")
        for q in rq or []:
            for r in q.get("rewards", []):
                iid = r.get("id")
                if not isinstance(iid, int): continue
                lst = quests.setdefault(iid, [])
                if not any(x["qid"] == q["id"] for x in lst):
                    lst.append({"qid": q["id"], "title": q["name"], "lvl": 0}); n2 += 1
        print(f"{slug}: inst={inst!r} drops+{n1} quest rewards+{n2}")
    q = lambda s: json.dumps(s, ensure_ascii=False)
    with open(a.out, "w", encoding="utf-8") as f:
        f.write("-- AUTO-GENERATED by tools/extract_dungeon_data.py. Do not hand edit.\n")
        f.write("-- Dungeon boss loot and quest rewards.\n")
        f.write("local _, ns = ...\nns.DungeonData = {\n    drops = {\n")
        for iid in sorted(drops):
            f.write("        [%d] = { %s },\n" % (iid, ", ".join("{inst=%s, boss=%s}" % (q(x["inst"]), q(x["boss"])) for x in drops[iid])))
        f.write("    },\n    quests = {\n")
        for iid in sorted(quests):
            f.write("        [%d] = { %s },\n" % (iid, ", ".join("{qid=%d, title=%s, lvl=%d}" % (x["qid"], q(x["title"]), x["lvl"]) for x in quests[iid])))
        f.write("    },\n}\n")
    print("drops items:", len(drops), "quest reward items:", len(quests))

if __name__ == "__main__":
    main()
