#!/usr/bin/env python3
"""지역 페이지(상인/획득 가능 아이템)와 희귀 몹 목록에서 장비 획득처를 뽑아 WorldData.lua 를 만든다.

사용법:  DUNGEON_DATA_BASE=<사이트 주소/en> python3 tools/extract_world_data.py --out WorldData.lua [--cache DIR]
  - 희귀 몹(발견 페이지): 몹 이름, 지역, 드랍 아이템  -> drops
  - 지역 페이지 '상인' 묶음                            -> vendors
  - 지역 페이지 '획득 가능 아이템' 중 퀘스트 보상        -> quests, 몹 드랍 -> drops, 평판 -> vendors
"""
import os, re, json, argparse, urllib.request
from pathlib import Path

BASE = os.environ.get("DUNGEON_DATA_BASE", "")
TITLE = r'"font-serif text-base font-bold text-gold-2","children":"([^"]+)"'

def get(path, cache):
    p = Path(cache) / (path.strip("/").replace("/", "_") + ".html") if cache else None
    if p and p.exists():
        return p.read_text(encoding="utf-8")
    req = urllib.request.Request(BASE + path, headers={"User-Agent": "Mozilla/5.0 BestGearFinder-data"})
    h = urllib.request.urlopen(req, timeout=60).read().decode("utf-8")
    if p:
        p.parent.mkdir(parents=True, exist_ok=True); p.write_text(h, encoding="utf-8")
    return h

def flight(h):
    parts = re.findall(r'self\.__next_f\.push\(\[1,"(.*?)"\]\)</script>', h, flags=re.S)
    return "".join(json.loads('"' + p + '"') for p in parts)

def section(t, sid):
    i = t.find(f'"aria-labelledby":"{sid}"')
    if i < 0: return ""
    j = t.find('"aria-labelledby":"', i + 30)
    return t[i:j if j > 0 else len(t)]

def groups(seg):
    titles = [(m.start(), m.group(1)) for m in re.finditer(TITLE, seg)]
    for k, (p, ti) in enumerate(titles):
        e = titles[k + 1][0] if k + 1 < len(titles) else len(seg)
        yield ti, [int(x) for x in re.findall(r'"item":\{"id":(\d+)', seg[p:e])]

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="WorldData.lua")
    ap.add_argument("--cache")
    a = ap.parse_args()
    drops, vendors, quests = {}, {}, {}
    def add(tbl, iid, entry, key):
        lst = tbl.setdefault(iid, [])
        if not any(all(x.get(k) == entry.get(k) for k in key) for x in lst): lst.append(entry)
    # 희귀 몹
    t = flight(get("/discoveries", a.cache))
    dec = json.JSONDecoder()
    for m in re.finditer(r'\{"npc":(\d+),"name":"', t):
        try:
            obj, _ = dec.raw_decode(t[m.start():])
        except ValueError:
            continue
        zone = obj.get("zone") if obj.get("zone") != "$undefined" else ""
        for d in obj.get("drops") or []:
            it = d.get("item") if isinstance(d, dict) else None
            if isinstance(it, dict) and isinstance(it.get("id"), int):
                add(drops, it["id"], {"inst": zone or "?", "boss": obj["name"], "npc": obj["npc"]}, ("boss",))
    # 지역 페이지
    zl = flight(get("/zones", a.cache)) + get("/zones", a.cache)
    slugs = []
    for m in re.finditer(r'/zones/([a-z0-9-]+)', zl):
        if m.group(1) not in slugs: slugs.append(m.group(1))
    for slug in slugs:
        try:
            t = flight(get("/zones/" + slug, a.cache))
        except Exception as e:
            print("skip", slug, e); continue
        mm = re.search(r'"id":"zone-title"[^}]*"children":"([^"]+)"', t) or re.search(r'<h1[^>]*>([^<]+)</h1>', get("/zones/" + slug, a.cache))
        zone = mm.group(1).strip() if mm else slug.replace("-", " ").title()
        for title, ids in groups(section(t, "vendors")):
            for iid in ids: add(vendors, iid, {"zone": zone, "boss": title}, ("zone", "boss"))
        for title, ids in groups(section(t, "items")):
            low = title.lower()
            for iid in ids:
                if "quest" in low: add(quests, iid, {"title": zone, "qid": 0, "lvl": 0}, ("title",))
                elif "drop" in low: add(drops, iid, {"inst": zone, "boss": ""}, ("inst", "boss"))
                elif "reputation" in low: add(vendors, iid, {"zone": zone, "boss": title}, ("zone", "boss"))
    q = lambda s: json.dumps(s, ensure_ascii=False)
    with open(a.out, "w", encoding="utf-8") as f:
        f.write("-- AUTO-GENERATED by tools/extract_world_data.py. Do not hand edit.\n")
        f.write("-- Rare mob drops, zone vendors and zone quest rewards.\nlocal _, ns = ...\nns.WorldData = {\n")
        f.write("    drops = {\n")
        for iid in sorted(drops):
            f.write("        [%d] = { %s },\n" % (iid, ", ".join("{inst=%s, boss=%s%s}" % (q(x["inst"]), q(x["boss"]), (", npc=%d" % x["npc"]) if x.get("npc") else "") for x in drops[iid])))
        f.write("    },\n    vendors = {\n")
        for iid in sorted(vendors):
            f.write("        [%d] = { %s },\n" % (iid, ", ".join("{zone=%s, boss=%s}" % (q(x["zone"]), q(x["boss"])) for x in vendors[iid])))
        f.write("    },\n    quests = {\n")
        for iid in sorted(quests):
            f.write("        [%d] = { %s },\n" % (iid, ", ".join("{qid=0, title=%s, lvl=0}" % q(x["title"]) for x in quests[iid])))
        f.write("    },\n}\n")
    print("zones", len(slugs), "drops", len(drops), "vendors", len(vendors), "quests", len(quests))

if __name__ == "__main__":
    main()
