#!/usr/bin/env python3
"""BiS 목록(HTML 저장본) -> BiSData.lua

사용법:  python3 tools/extract_bis.py <html 폴더> > BiSData.lua
  <html 폴더> 에는 druid.html, warrior.html ... (직업별 BiS 페이지 저장본)이 있어야 한다.
  각 페이지에 들어 있는 JSON(tabs)에서 PvE 목록만 읽어,
  슬롯별 1순위 아이템(top)과 대안 아이템(alt)의 ID 를 모은다.
"""
import json, re, sys
from pathlib import Path

CLASSES = ["warrior", "paladin", "hunter", "rogue", "priest", "shaman", "mage", "warlock", "druid"]

def payload(path):
    s = Path(path).read_text(encoding="utf-8", errors="replace")
    parts = [json.loads(m.group(1)) for m in re.finditer(r'self\.__next_f\.push\(\[1,("(?:[^"\\]|\\.)*")\]\)', s)]
    return "".join(parts)

def tabs(path):
    t = payload(path)
    i = t.find('"tabs":[')
    obj, _ = json.JSONDecoder().raw_decode(t[i + len('"tabs":'):])
    return obj

def resolve(tb, v, depth=0):
    """페이지가 중복을 줄이려고 쓰는 참조("$23:props:tabs:0:spec:...:item")를 실제 값으로 바꾼다."""
    while isinstance(v, str) and v.startswith("$") and ":tabs:" in v and depth < 8:
        node = tb
        for tok in v.split(":tabs:", 1)[1].split(":"):
            node = node[int(tok)] if isinstance(node, list) else node[tok]
        v = node
        depth += 1
    return v

def main(folder):
    out = {}
    for c in CLASSES:
        res = {}
        tb = tabs(Path(folder) / f"{c}.html")
        for tab in tb:
            if tab.get("mode") != "pve":
                continue
            sides = {}
            for sname, side in tab["spec"]["sides"].items():
                top, alt = [], []
                for slot, opts in side["options"].items():
                    for n, o in enumerate(opts):
                        iid = resolve(tb, o["item"])["id"]
                        (top if n == 0 else alt).append(iid)
                top = sorted(set(top))
                alt = sorted(set(alt) - set(top))
                sides[sname[0].upper()] = (top, alt)      # "A" 얼라이언스 / "H" 호드
            res[tab["id"]] = sides
        out[c.upper()] = res
    w = sys.stdout.write
    w("-- AUTO-GENERATED by tools/extract_bis.py. Do not hand edit.\n")
    w("-- Level-30 BiS lists (PvE), used here for the BiS marker.\n")
    w("local _, ns = ...\n")
    w("ns.BiS = {\n")
    for cls, res in out.items():
        w(f"    {cls} = {{\n")
        for tid, sides in res.items():
            parts = []
            for sk, (top, alt) in sorted(sides.items()):
                parts.append(f'{sk} = {{ top = {{{",".join(map(str, top))}}}, alt = {{{",".join(map(str, alt))}}} }}')
            w(f'        ["{tid}"] = {{ {", ".join(parts)} }},\n')
        w("    },\n")
    w("}\n")

if __name__ == "__main__":
    main(sys.argv[1])
