#!/usr/bin/env python3
"""전문기술 제조법 데이터(Lua) -> CraftData.lua

사용법:  python3 tools/extract_craft_data.py <제조법 Data.lua> --geardb GearDatabase.lua --out CraftData.lua
  <제조법 Data.lua> 는 ns.Data[직업ID] = { recipes = { {주문ID, 아이템ID, 분류, 배우는숙련, ..., 출처(한국어), 출처(영어)} } } 형식.
  만들어지는 아이템 중 CMaNGOS 제작 데이터(GearDatabase.lua)에 없는 것만 담는다. 장비 여부는 게임에서 다시 거른다.
"""
import argparse, re
from lupa import LuaRuntime

PROF = {171: "연금술", 164: "대장기술", 333: "마법부여", 202: "기계공학", 165: "가죽세공",
        197: "재봉술", 186: "채광", 185: "요리", 129: "응급치료"}
NO_RECIPE = ("", "교관", "기본 제조법")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src")
    ap.add_argument("--geardb", default="GearDatabase.lua")
    ap.add_argument("--out", default="CraftData.lua")
    a = ap.parse_args()
    g = open(a.geardb, encoding="utf-8").read()
    i = g.find("crafting = {")
    known = set(int(x) for x in re.findall(r"\[(\d+)\] = \{", g[i:])) if i >= 0 else set()
    L = LuaRuntime(unpack_returned_tuples=True)
    ns = L.table()
    L.execute("return function(src, ns) local fn = assert(load(src)); return fn('x', ns) end")(open(a.src, encoding="utf-8").read(), ns)
    out = {}
    for line in ns.Data.keys():
        prof = PROF.get(int(line))
        if not prof: continue
        recs = ns.Data[line].recipes
        for k in range(1, len(recs) + 1):
            r = recs[k]
            item, spell, lvl = int(r[2] or 0), int(r[1] or 0), int(r[4] or 0)
            if item <= 0 or item in known: continue
            src = (r[16] or "")
            need = src.split(" · ")[0] not in NO_RECIPE
            lst = out.setdefault(item, [])
            if not any(e[0] == prof for e in lst):
                lst.append((prof, lvl, need, spell))
    with open(a.out, "w", encoding="utf-8") as f:
        f.write("-- AUTO-GENERATED by tools/extract_craft_data.py. Do not hand edit.\n")
        f.write("-- Crafted items not in the CMaNGOS data: profession, skill to learn, whether a recipe is needed.\n")
        f.write("local _, ns = ...\nns.CraftData = {\n    craft = {\n")
        for item in sorted(out):
            f.write("        [%d] = { %s },\n" % (item, ", ".join(
                '{skill="%s", lvl=%d, recipe=%s, spell=%d}' % (p, l, "true" if n else "false", s) for p, l, n, s in out[item])))
        f.write("    },\n}\n")
    print("craft items:", len(out))

if __name__ == "__main__":
    main()
