#!/usr/bin/env python3
"""영어 보스·몹·지역 이름 -> 한국어 이름 표 (NamesKO.lua)

사용법:  python3 tools/extract_names.py --pages <던전 페이지 캐시 폴더> [--drg <DungeonRouteGuide Data.lua>] --out NamesKO.lua
  - 던전 페이지(영어 <slug>.html / 한국어 <slug>.ko.html)의 우두머리 목록과 전리품의 보스 이름을 짝지음
  - Dungeon Route Guide 의 Data.lua 에 있는 name = { ko = ..., en = ... } 짝
  - 클래식 지역 이름은 아래 표
"""
import re, json, argparse, glob, os

ZONES = {
    "Elwynn Forest": "엘윈 숲", "Westfall": "서부 몰락지대", "Redridge Mountains": "붉은마루 산맥", "Duskwood": "그늘숲",
    "Stranglethorn Vale": "가시덤불 골짜기", "Dun Morogh": "던 모로", "Loch Modan": "모단 호수", "Wetlands": "저습지",
    "Arathi Highlands": "아라시 고원", "Hillsbrad Foothills": "힐스브래드 구릉지", "Alterac Mountains": "알터랙 산맥",
    "Silverpine Forest": "은빛소나무 숲", "Tirisfal Glades": "티리스팔 숲", "The Barrens": "불모의 땅", "Durotar": "듀로타",
    "Mulgore": "멀고어", "Teldrassil": "텔드랏실", "Darkshore": "어둠의 해안", "Ashenvale": "잿빛 골짜기",
    "Stonetalon Mountains": "돌발톱 산맥", "Thousand Needles": "버섯구름 봉우리", "Desolace": "잊혀진 땅",
    "Dustwallow Marsh": "먼지진흙 습지대", "Badlands": "황야의 땅", "Searing Gorge": "이글거리는 협곡",
    "Burning Steppes": "불타는 평원", "Swamp of Sorrows": "슬픔의 늪", "Blasted Lands": "저주받은 땅", "Feralas": "페랄라스",
    "Tanaris": "타나리스", "Azshara": "아즈샤라", "Felwood": "악령의 숲", "Un'Goro Crater": "운고로 분화구",
    "Winterspring": "여명의 설원", "Silithus": "실리더스", "Moonglade": "달의 숲", "Western Plaguelands": "서부 역병지대",
    "Eastern Plaguelands": "동부 역병지대", "The Hinterlands": "동부 내륙지", "Deadwind Pass": "죽음의 고개",
    "Stormwind City": "스톰윈드", "Ironforge": "아이언포지", "Orgrimmar": "오그리마", "Thunder Bluff": "썬더 블러프",
    "Undercity": "언더시티", "Darnassus": "다르나서스", "Blackrock Mountain": "검은바위 산",
    "Deadmines": "죽음의 폐광", "The Deadmines": "죽음의 폐광", "Razorfen Kraul": "가시덩굴 우리",
    "Wailing Caverns": "통곡의 동굴", "Shadowfang Keep": "그림자송곳니 성채", "Blackfathom Deeps": "검은심연의 나락",
    "The Stockade": "스톰윈드 지하감옥", "Stockade": "스톰윈드 지하감옥", "Gnomeregan": "놈리건", "Ragefire Chasm": "성난불길 협곡",
    "Razorfen Downs": "가시덩굴 구릉", "Scarlet Monastery": "붉은십자군 수도원", "Uldaman": "울다만",
    "Dalaran": "달라란", "Hall of Thanes": "영주의 전당", "Ruins of Lordaeron": "로데론의 폐허",
}

def flight(h):
    parts = re.findall(r'self\.__next_f\.push\(\[1,"(.*?)"\]\)</script>', h, flags=re.S)
    return "".join(json.loads('"' + p + '"') for p in parts)

def arr(t, key):
    i = t.find(f'"{key}":[')
    if i < 0: return []
    o, _ = json.JSONDecoder().raw_decode(t[i + len(key) + 3:])
    return o

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pages"); ap.add_argument("--drg"); ap.add_argument("--out", default="NamesKO.lua")
    a = ap.parse_args()
    boss = {}
    def put(en, ko):
        if not (en and ko) or en == ko or en == "$undefined" or ko == "$undefined": return
        # "A · B · C" 처럼 여러 이름이 묶인 것은 하나씩 나눠서도 넣는다
        es, ks = [x.strip() for x in re.split(r"\s*[·/]\s*", en)], [x.strip() for x in re.split(r"\s*[·/]\s*", ko)]
        if len(es) > 1 and len(es) == len(ks):
            for e1, k1 in zip(es, ks):
                if e1 and k1 and e1 not in boss: boss[e1] = k1
        if en not in boss: boss[en] = ko
    if a.pages:
        for ko_path in glob.glob(os.path.join(a.pages, "*.ko.html")):
            en_path = ko_path[:-8] + ".html"
            if not os.path.exists(en_path): continue
            tk, te = flight(open(ko_path, encoding="utf-8").read()), flight(open(en_path, encoding="utf-8").read())
            for b in arr(tk, "bosses"):
                put(b.get("nameEn"), b.get("name"))
            lk = {x["id"]: x for x in arr(tk, "loot") if isinstance(x, dict) and "id" in x}
            for x in arr(te, "loot"):
                y = lk.get(x.get("id")) if isinstance(x, dict) else None
                if y: put(x.get("bossName"), y.get("bossName"))
    if a.drg and os.path.exists(a.drg):
        s = open(a.drg, encoding="utf-8").read()
        for m in re.finditer(r'name = \{ ko = "([^"]+)", en = "([^"]+)" \}', s):
            put(m.group(2), m.group(1))
    q = lambda t: json.dumps(t, ensure_ascii=False)
    with open(a.out, "w", encoding="utf-8") as f:
        f.write("-- AUTO-GENERATED by tools/extract_names.py. Do not hand edit.\n-- English boss / mob / zone names -> Korean.\nlocal _, ns = ...\nns.NamesKO = {\n    boss = {\n")
        for en in sorted(boss): f.write("        [%s] = %s,\n" % (q(en), q(boss[en])))
        f.write("    },\n    zone = {\n")
        for en in sorted(ZONES): f.write("        [%s] = %s,\n" % (q(en), q(ZONES[en])))
        f.write("    },\n}\n")
    print("boss names", len(boss), "zones", len(ZONES))

if __name__ == "__main__":
    main()
